cqfn/pdd

- lib/pdd/source.rb
- test/test_source.rb
Use github search api to obtain github login using author email
> #105 pdd should store github user name not real name

- features/rake.feature
- features/step_definitions/steps.rb
- lib/pdd/rake_task.rb
- test/test_rake_task.rb
This fixes #114. I've added a skeleton without implementation but with PDD todos.
> #114 Add the new Rake task without implementation

- .gitignore
- features/rake.feature
- features/support/env.rb
- pdd.gemspec
This is a fix to #126. I've tried to use Aruba to catch stderr.
> #126 Start using aruba to test stderr.

- features/rake.feature
This is the fix for #135. I've replaced `run` to `run the following commands with bash`. And no one warning about deprecated methods in not shown up.
> #135 Replacing run to run following commands

- features/catches_broken_puzzles.feature
- lib/pdd/source.rb
- test/test_source.rb
This fix is backwards compatible. I think in other to prevent micro configurations/rules that are not essential to the generation of puzzles e.g setting configuration option for max number of leading spaces, it is best to remove that restriction on the number of leading spaces on the next line of a puzzle.
That's the idea behind this solution :)
> #149: remove restriction on max number of leading spaces on next line

- README.md
Add documentation for `TODO:` and `TODO` markers.
> #115: document other todo markers in README

- Rakefile
- lib/pdd/source.rb
- test/test_source.rb
The issue fixed here is due to the following facts:
1. that empty queries to get a user from github API returns all users with Linus Torvalds as the first user in the list.
2. some users have their github email as private (see screenshot), therefore their data can't be queried with the email. The fallback is to query with the user's fullname provided that is also defined.
Screenshot:
> #155: fix bug with github username query

- lib/pdd/source.rb
- test/test__helper.rb
- test/test_source.rb
- test/test_source_todo.rb
Parses these markers correctly ✅ 
```
// @todo: #85 Another marker
// @todo: #85 Yet another marker
```
Resolves #96
> #96: allow markers on contiguous lines

- features/catches_broken_puzzles.feature
- lib/pdd/source.rb
> #165: format error/warn message with file link

- pdd.gemspec
Use pessimistic update ~> 2.3. 
Note: Ruby 2.3 is EOL. And it will be good to have a new version like ~2.7.
> [#113] use pessimistic version constraint

- README.md
- lib/pdd.rb
- test/test_source.rb
- test/test_source_todo.rb
Save puzzle content with UTF-8 encoding
Also resolves #143
> [#164] save puzzle content as utf-8

- README.md
It's also a formatting rule, not quiet obvious, but the known error happens with 0pdd when there are duplicates.
See [PR with error message](https://github.com/rocket-3/dbmss/pull/20)
> Add a note and some formatting in readme.md/How to format

- features/catches_broken_puzzles.feature
- features/parsing.feature
- lib/pdd/source.rb
- test/test_source.rb
- test/test_source_todo.rb
Example:
Here's an example puzzle
```
#
#
#
def greeting:
print('Hello')
```
> [#163] Use blank lines instead of indentation as issue body markers

- .rubocop.yml
- lib/pdd/source.rb
- utils/glob.rb
> [#197] Avoiding repeated calls

- .rubocop.yml
- lib/pdd/source.rb
- test/test_source.rb
- use spaces as indentation for puzzle body when no line comment prefix is found
> [#207] fix wrongly detected puzzle body

- features/cli.feature
- lib/pdd/source.rb
- test/test_source.rb
Examples:
```
/*
* @todo #42 hello
*  good bye
* hello again
*/
```
Puzzle body: `hello good bye`
> [#209] mark end of puzzle body where indentation stops

- lib/pdd/source.rb
- test/test_source_todo.rb
1. Check for puzzle maker only TODO followed by : or space 
2. add require_relative 'test_helper' to run one file with tests (as described in README)
> [#226] Check for puzzle maker only TODO followed by : or space 

- README.md
Add installation part with Ruby (and minimum version) and Libmagic
> [#227] update installation info

- bin/pdd
- features/cli.feature
- features/step_definitions/steps.rb
1. Lines with # in the beginning of the .gitignore content are ignored
2. Enable tests for --skip-gitignore option
> [#222] Ignore comments from .gitignore file 

- lib/pdd/source.rb
- test/test_source.rb
- test/test_source_todo.rb
- test_assets/puzzles/44-660e9d6f
1. Empty comment line is supposed to be as end of the puzzle description
2. If comment contains space symbol it is still considered as puzzle description
> [#234] Empty line is supposed as stop for puzzle description

- Gemfile
- README.md
- Rakefile
- features/step_definitions/steps.rb
- lib/pdd/source.rb
- test/test_source.rb
- test/test_source_todo.rb
- test_assets/puzzles/44-660e9d6f
1. Examples for multiline puzzles
2. Remove unsupported examples
Fix #224
> [#224] Add description for multiline puzzle
