cqfn/pdd

assets/puzzles.xsd, lib/pdd/source.rb, test/test_source.rb
=> #85 Skip invalid emails.

test/test_sources.rb
=> Test for recursive exclusion of directories

lib/pdd/sources.rb, test/test_source.rb
Fix some broken tests for #98.
=> (#98) Fix broken tests

lib/pdd/source.rb, test/test_source_todo.rb
Added TODO and TODO: tags support for pdd puzzles
=> #106 allow TODO and TODO: tags for pdd puzzles

.travis.yml
This fixes #121. I've chosen the minimal version that the build is passed.
=> #121 Fix the ruby version in the travis build.

.rubocop.yml, bin/pdd
This fixes #119. I've enabled the rubocop on the bin dir and fixed some of its errors.
=> #119 Enable the rubocop on bin/ and fix its errors

lib/pdd/rake_task.rb, test/test_rake_task.rb
This is a fix for #125. I've added a basic implementation of the rake task with parsing the name parameter.
=> #125 Add parsing the name parameter from the rake task.

.rubocop.yml, lib/pdd.rb, pdd.gemspec
This is a fix for #123. I've updated a Ruby version and fixed some errors.
=> #123 Update the ruby version and fix rubocop errors

.simplecov, Gemfile, LICENSE.txt, Rakefile, assets/puzzles.xsd, assets/puzzles.xsl, bin/pdd, features/step_definitions/steps.rb, features/support/env.rb, lib/pdd.rb, lib/pdd/puzzle.rb, lib/pdd/rule/duplicates.rb, lib/pdd/rule/estimates.rb, lib/pdd/rule/roles.rb, lib/pdd/rule/text.rb, lib/pdd/source.rb, lib/pdd/sources.rb, lib/pdd/version.rb, pdd.gemspec, test/test__helper.rb, test/test_duplicates.rb, test/test_estimates.rb, test/test_pdd.rb, test/test_roles.rb, test/test_source.rb, test/test_source_todo.rb, test/test_sources.rb, test/test_text.rb
=> #153: year is up, bug is puzzled

.pdd, bin/pdd, lib/pdd.rb, lib/pdd/source.rb, test/test_pdd.rb, test/test_source.rb
Went with `--skip-errors` flag
=> #156: add --skip-errors option

.overcommit.yml, README.md
Add pre-commit and pre-push hooks to automatically lint and run tests. All rake tasks have been added except features because one feature fails with overcommit (will investigate in another issue since that's not the goal of this one)
=> [#167] add overcommit to configure git hooks

.overcommit.yml, .rubocop.yml, .simplecov, bin/pdd, features/step_definitions/steps.rb, lib/pdd.rb, lib/pdd/rake_task.rb, lib/pdd/rule/duplicates.rb, lib/pdd/rule/roles.rb, lib/pdd/rule/text.rb, lib/pdd/source.rb, lib/pdd/sources.rb, pdd.gemspec, test/test__helper.rb, test/test_pdd.rb, test/test_source.rb
General catch-all task for fixes, codestyle refactoring that are not related with a specific issue.
According to the style guide Ruby that recommends best practices
https://rubystyle.guide/
=> #158: Refactoring/codestyle

.gitignore, bin/pdd, lib/pdd.rb
Exclude files in .gitignore from pdd when `--skip-gitignore` is set
=> [#80] exclude files from .gitignore

README.md
I slightly changed the Readme file and added examples and descriptions for supported PDD options. This is a fix of issue #174
=> [#174] Some of supported options for PDD are not listed in the README.md

.pdd, bin/pdd, features/cli.feature, features/html_output.feature, features/uses_config.feature, lib/pdd.rb, lib/pdd/rake_task.rb, lib/pdd/sources.rb, pdd.gemspec, test/test_sources.rb
- Refactor code for including and excluding files
- Updated tests
- Allow all exclusion and inclusion relative to source directory
=> #176 only include or exclude relative to source

lib/pdd.rb, lib/pdd/sources.rb, utils/glob.rb
All values are in seconds
| Description  | CPU time | Kernel time | Total time | Real (clock) time |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Previous | 117.396410  | 4.412440  | 122.288659  | 133.210167 |
| Now | 0.204576  | 1.167331  | 1.639570  | 5.352543 |
=> [#184] improve project scan time

.simplecov, Gemfile, LICENSE.txt, Rakefile, assets/puzzles.xsd, assets/puzzles.xsl, bin/pdd, features/step_definitions/steps.rb, features/support/env.rb, lib/pdd.rb, lib/pdd/puzzle.rb, lib/pdd/rule/duplicates.rb, lib/pdd/rule/estimates.rb, lib/pdd/rule/roles.rb, lib/pdd/rule/text.rb, lib/pdd/source.rb, lib/pdd/sources.rb, lib/pdd/version.rb, pdd.gemspec, test/test__helper.rb, test/test_duplicates.rb, test/test_estimates.rb, test/test_pdd.rb, test/test_roles.rb, test/test_source.rb, test/test_source_todo.rb, test/test_sources.rb, test/test_text.rb, utils/glob.rb
Update copyright date
Resolves #188
=> [#188] update copryright date

lib/pdd/rake_task.rb
Issue 133 - after discussion we decided that this puzzle was useless for now
=> [#133] Avoiding unnecessary methods

.pdd, Rakefile, assets/puzzles_json.xsl, bin/pdd, cucumber.yml, features/json_output.feature, features/step_definitions/steps.rb
Formatting report to json format
=> [#223] JSON report

.github/workflows/codecov.yml, Gemfile, test/test__helper.rb
=> [#238] Formatter is required for codecov report

.github/workflows/codecov.yml, .simplecov, README.md
- Add codecov check to PR creation
- Change url in codecov 
- Threshold is 90 (real is more then 96)
Fix https://github.com/cqfn/pdd/issues/238
=> [#238] Add codecov to pr creation
